tests: fix regression test for its8521.
Change-Id: I087b50943151b4e5cd4683e1e9c63f28ddc67a61

diff --git a/tests/data/regressions/its8521/its8521 b/tests/data/regressions/its8521/its8521
--- a/tests/data/regressions/its8521/its8521
+++ b/tests/data/regressions/its8521/its8521
@@ -1,9 +1,9 @@
-#! /bin/sh
-# $OpenLDAP$
-## This work is part of OpenLDAP Software <http://www.openldap.org/>.
-##
-## Copyright 1998-2016 The OpenLDAP Foundation.
+#!/bin/bash
+## $ReOpenLDAP$
+## Copyright 1998-2016 ReOpenLDAP AUTHORS: please see AUTHORS file.
 ## All rights reserved.
+##
+## This file is part of ReOpenLDAP.
 ##
 ## Redistribution and use in source and binary forms, with or without
 ## modification, are permitted only as authorized by the OpenLDAP
@@ -16,7 +16,7 @@
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-if test $SYNCPROV = syncprovno; then
+if test ${AC_conf[syncprov]} = no; then
 	echo "Syncrepl provider overlay not available, test skipped"
 	exit 0
 fi
@@ -41,8 +41,15 @@ ITS=8521
 ITSDIR=$DATADIR/regressions/its$ITS
 
 echo "Starting provider slapd on TCP/IP port $PORT1..."
-. $CONFFILTER $BACKEND $MONITORDB < $ITSDIR/slapd-provider.ldif > $CONFLDIF
+config_filter $BACKEND ${AC_conf[monitor]} < $ITSDIR/slapd-provider.ldif > $CONFLDIF
 $SLAPADD -F $CFPRO -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed: -F $CFPRO -n 0 -l $CONFLDIF ($RC)"
+	killservers
+	exit $RC
+fi
+
 $SLAPD -F $CFPRO -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
@@ -67,13 +74,20 @@ done
 
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
 echo "Starting consumer slapd on TCP/IP port $PORT2..."
-. $CONFFILTER $BACKEND $MONITORDB < $ITSDIR/slapd-consumer.ldif > $CONFLDIF
+config_filter $BACKEND ${AC_conf[monitor]} < $ITSDIR/slapd-consumer.ldif > $CONFLDIF
 $SLAPADD -F $CFCON -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed: -F $CFCON -n 0 -l $CONFLDIF ($RC)"
+	killservers
+	exit $RC
+fi
+
 $SLAPD -F $CFCON -h $URI2 -d $LVL $TIMING > $LOG2 2>&1 &
 SLAVEPID=$!
 if test $WAIT != 0 ; then
@@ -159,7 +173,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-if [ "$SYNCPROV" = syncprovmod ]; then
+if [ ${AC_conf[syncprov]} = mod ]; then
 	echo "Configuring syncprov module on the provider..."
 	$LDAPADD -D cn=config -H $URI1 -y $CONFIGPWF <<EOF > $TESTOUT 2>&1
 dn: cn=module,cn=config
@@ -218,16 +232,16 @@ add: olcSyncrepl
 olcSyncrepl: rid=100 provider=$URI1 bindmethod=simple
   binddn="cn=replicator,ou=LDAPRoles,dc=example,dc=com" credentials=secret
   type=refreshAndPersist searchbase="dc=example,dc=com" filter="(objectclass=*)"
-  scope=sub schemachecking=on interval=5 retry="5 +" sizeLimit=unlimited
+  scope=sub schemachecking=on interval=1 retry="$SYNCREPL_RETRY" timeout=1 sizeLimit=unlimited
   timelimit=unlimited
 -
 
 EOF
 RC=$?
 if test $RC != 0 ; then
-  echo "ldapmodify failed for olcSyncrepl configuration ($RC)!"
-  test $KILLSERVERS != no && kill -HUP $KILLPIDS
-  exit $RC
+	echo "ldapmodify failed for olcSyncrepl configuration ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
 fi
 
 echo "Sleeping 10 seconds to allow replication to initiate..."
@@ -235,27 +249,26 @@ sleep 10
 
 echo "Using ldapsearch to read all the entries from the provider..."
 $LDAPSEARCH -S "" -D $MANAGERDN -w $PASSWD -b "$BASEDN" -H $URI1 \
-        '(objectclass=*)' '*' $OPATTRS > $MASTEROUT 2>&1
+	'(objectclass=*)' '*' $OPATTRS > $MASTEROUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
-        echo "ldapsearch failed at provider ($RC)!"
-        test $KILLSERVERS != no && kill -HUP $KILLPIDS
-        exit $RC
+	echo "ldapsearch failed at provider ($RC)!"
+	killservers
+	exit $RC
 fi
 
 echo "Using ldapsearch to read all the entries from the consumer..."
 $LDAPSEARCH -S "" -D $MANAGERDN -w $PASSWD -b "$BASEDN" -H $URI2 \
-        '(objectclass=*)' '*' $OPATTRS > $SLAVEOUT 2>&1
+	'(objectclass=*)' '*' $OPATTRS > $SLAVEOUT 2>&1
 RC=$?
 
 if test $RC == 0 ; then
-        echo "ldapsearch succeeded at consumer ($RC)!"
+	echo "ldapsearch succeeded at consumer ($RC)!"
 	echo "This is a regression of ITS8281"
-        test $KILLSERVERS != no && kill -HUP $KILLPIDS
-        exit $RC
+	killservers
+	exit $RC
 fi
-
 
 echo "Filtering provider results..."
 $LDIFFILTER < $MASTEROUT > $MASTERFLT
@@ -266,15 +279,15 @@ echo "Comparing retrieved entries from provider and consumer..."
 $CMP $MASTERFLT $SLAVEFLT > $CMPOUT
 
 if test $? == 0 ; then
-        echo "test failed - provider and consumer databases match"
+	echo "test failed - provider and consumer databases match"
 	echo "This is a regression of ITS8281"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-        exit 1
+	killservers
+	exit 1
 fi
 
 echo "Modifying provider to force generation of a contextCSN"
 $LDAPMODIFY -v -D "$MANAGERDN" -H $URI1 -w $PASSWD > \
-        $TESTOUT 2>&1 << EOMODS
+	$TESTOUT 2>&1 << EOMODS
 dn: uid=Johndoe,dc=users,dc=example,dc=com
 changetype: modify
 replace: cn
@@ -290,14 +303,14 @@ $LDAPSEARCH -S "" -D $MANAGERDN -w $PASSWD -b "$BASEDN" -H $URI1 \
 RC=$?
 
 if test $RC != 0 ; then
-        echo "ldapsearch failed at provider ($RC)!"
-        test $KILLSERVERS != no && kill -HUP $KILLPIDS
-        exit $RC
+	echo "ldapsearch failed at provider ($RC)!"
+	killservers
+	exit $RC
 fi
 
 echo "Using ldapsearch to read all the entries from the consumer..."
 $LDAPSEARCH -S "" -D $MANAGERDN -w $PASSWD -b "$BASEDN" -H $URI2 \
-        '(objectclass=*)' '*' $OPATTRS > $SLAVEOUT 2>&1
+	'(objectclass=*)' '*' $OPATTRS > $SLAVEOUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
