tests: rework/cleanup its8800 regression test.
Change-Id: I25b9359ab02957519359ec317589ef8bedea4084

diff --git a/tests/data/regressions/its8800/its8800 b/tests/data/regressions/its8800/its8800
--- a/tests/data/regressions/its8800/its8800
+++ b/tests/data/regressions/its8800/its8800
@@ -1,9 +1,9 @@
-#! /bin/bash
-# $OpenLDAP$
-## This work is part of OpenLDAP Software <http://www.openldap.org/>.
-##
-## Copyright 1998-2016 The OpenLDAP Foundation.
+#!/bin/bash
+## $ReOpenLDAP$
+## Copyright 1998-2018 ReOpenLDAP AUTHORS: please see AUTHORS file.
 ## All rights reserved.
+##
+## This file is part of ReOpenLDAP.
 ##
 ## Redistribution and use in source and binary forms, with or without
 ## modification, are permitted only as authorized by the OpenLDAP
@@ -14,25 +14,24 @@
 ## <http://www.OpenLDAP.org/license.html>.
 
 echo "running defines.sh"
-. $SRCDIR/scripts/defines.sh
+. ${TOP_SRCDIR}/tests/scripts/defines.sh
 
-if test $PPOLICY = ppolicyno; then
-        echo "Password policy overlay not available, test skipped"
-        exit 0
+if test ${AC_conf[ppolicy]} = no; then
+	echo "Password policy overlay not available, test skipped"
+	exit 0
 fi
-
-if test $SYNCPROV = syncprovno; then
+if test ${AC_conf[syncprov]} = no; then
 	echo "Syncrepl provider overlay not available, test skipped"
 	exit 0
 fi
-if test $ACCESSLOG = accesslogno; then
-        echo "Accesslog overlay not available, test skipped"
-        exit 0
+if test ${AC_conf[accesslog]} = no; then
+	echo "Accesslog overlay not available, test skipped"
+	exit 0
 fi
 if test $BACKEND = ldif ; then
-        # Onelevel search does not return entries in order of creation or CSN.
-        echo "$BACKEND backend unsuitable for syncprov logdb, test skipped"
-        exit 0
+	# Onelevel search does not return entries in order of creation or CSN.
+	echo "$BACKEND backend unsuitable for syncprov logdb, test skipped"
+	exit 0
 fi
 
 echo "This test tracks a case where changes are not refreshed when an old db is reloaded"
@@ -40,31 +39,26 @@ echo "See http://www.openldap.org/its/index.cgi/?findid=8800 for more informatio
 
 MMR=4
 XDIR=$TESTDIR/srv
-
 mkdir -p $TESTDIR
-
 $SLAPPASSWD -g -n >$CONFIGPWF
 
 ITS=8800
 ITSDIR=$DATADIR/regressions/its$ITS
 
-
-n=1
-while [ $n -le $MMR ]; do
+for ((n=1; n<=$MMR; n++)); do
 	echo "Initializing server configuration for MMR$n..."
 	DBDIR=${XDIR}$n/db
 	CFDIR=${XDIR}$n/slapd.d
 
 	mkdir -p ${XDIR}$n $DBDIR.1 $DBDIR.2 $CFDIR
-	. $CONFFILTER $BACKEND $MONITORDB < $ITSDIR/slapd-provider${n}.ldif > $CONFLDIF
+	DBNOSYNC=yes config_filter $BACKEND ${AC_conf[monitor]} < $ITSDIR/slapd-provider${n}.ldif > $CONFLDIF
+
 	$SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
 	$SLAPADD -F $CFDIR -q -b $BASEDN -l $ITSDIR/its8800db.ldif
-	n=`expr $n + 1`
 done
 
 KILLPIDS=
-n=1
-while [ $n -le $MMR ]; do
+for ((n=1; n<=$MMR; n++)); do
 	MYURI=`eval echo '$URI'$n`
 	MYLOG=`eval echo '$LOG'$n`
 	CFDIR=${XDIR}$n/slapd.d
@@ -79,58 +73,49 @@ while [ $n -le $MMR ]; do
 	fi
 	KILLPIDS="$PID $KILLPIDS"
 	PIDS[$n]="$PID"
-	sleep 1
-
-	echo "Using ldapsearch to check that provider slapd is running..."
-	for i in 0 1 2 3 4 5; do
-		$LDAPSEARCH -s base -b "" -H $MYURI \
-			'objectclass=*' > /dev/null 2>&1
-		RC=$?
-		if test $RC = 0 ; then
-			break
-		fi
-		echo "Waiting 5 seconds for slapd to start..."
-		sleep 5
-	done
-
-	if test $RC != 0 ; then
-		echo "ldapsearch failed ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-	n=`expr $n + 1`
+	check_running $n
 done
 
-echo "Sleeping 10 seconds to allow stabalization..."
-sleep 10
+# wait for sync
+for ((n=2; n<=$MMR; n++)); do
+	PORT=`eval echo '$PORT'$n`
+	wait_syncrepl $PORT1 $PORT base "" "-D $MANAGERDN -w $PASSWD"
+done
 
 echo "Looping failed authentications for 50 users 10 times each..."
-user=250
-while [ $user -le 300 ]; do
-	auths=1
-	echo -n "user $user..."
-	while [ $auths -le 10 ]; do
+for ((user=250; user<=300; user++)); do
+	echo -n "user $user"
+	for ((auths=1; auths<=10; auths++)); do
 		$LDAPSEARCH -x -H $URI1 -D uid=user.$user,ou=user,dc=example,dc=com -w wrongpass uid=fred >/dev/null 2>&1
 		RC=$?
 		if test $RC = 0 ; then
-			echo "ldapsearch succeeded when it should have failed"
-			exit 1
+			echo "ldapsearch succeeded when it should have failed ($RC)!"
+			killservers
+			exit $RC
 		fi
-		auths=`expr $auths + 1`
+		echo -n "."
 	done
-	echo "done"
-	user=`expr $user + 1`
+	echo " done"
 done
 
-echo -n "Sleeping 1 minute to ensure consumers catch up..."
-sleep 60
+SYNCREPL_WAIT=$((SYNCREPL_WAIT * 2))
+echo -n "Sleeping $SYNCREPL_WAIT seconds to ensure consumers catch up..."
+sleep $SYNCREPL_WAIT
 echo "done"
+for ((n=2; n<=$MMR; n++)); do
+	PORT=`eval echo '$PORT'$n`
+	wait_syncrepl $PORT1 $PORT base "" "-D $MANAGERDN -w $PASSWD"
+done
 
 echo -n "Stopping MMR1 slapd..."
 kill -HUP "${PIDS[1]}"
 wait ${PIDS[1]}
-sleep $SLEEP2
+sleep $SLEEP1
 echo "done"
+KILLPIDS=
+for ((n=2; n<=$MMR; n++)); do
+	KILLPIDS="${PIDS[$n]} $KILLPIDS"
+done
 
 echo -n "Wiping primary and accesslog databases for MMR1..."
 DBDIR="$TESTDIR/srv1/db"
@@ -150,63 +135,33 @@ if test $WAIT != 0 ; then
 	echo PID $PID
 	read foo
 fi
+check_running 1
 PIDS[1]=$PID
-sleep 1
+KILLPIDS="$PID $KILLPIDS"
 
-echo "Using ldapsearch to check that provider slapd is running..."
-for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -s base -b "" -H $URI1 \
-		'objectclass=*' > /dev/null 2>&1
-	RC=$?
-	if test $RC = 0 ; then
-		break
-	fi
-	echo "Waiting 5 seconds for slapd to start..."
-	sleep 5
+SYNCREPL_WAIT=$((SYNCREPL_WAIT * 2))
+echo "Sleeping $SYNCREPL_WAIT seconds to allow databases to sync..."
+sleep $SYNCREPL_WAIT
+for ((n=2; n<=$MMR; n++)); do
+	PORT=`eval echo '$PORT'$n`
+	wait_syncrepl $PORT1 $PORT base "" "-D $MANAGERDN -w $PASSWD" $((SYNCREPL_WAIT * 2)) $SLEEP1
 done
 
-n=1
-KILLPIDS=
-while [ $n -le 4 ]; do
-	KILLPIDS="${PIDS[$n]} $KILLPIDS"
-	n=`expr $n + 1`
-done
-
-if test $RC != 0 ; then
-	echo "ldapsearch failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-echo "done"
-
-echo "Sleeping 5 minutes to allow databases to sync..."
-sleep 300
-
+killservers
 echo "Comparing resulting databases..."
-
-n=1
-while [ $n -le 4 ]; do
+for ((n=1; n<=$MMR; n++)); do
 	CFDIR=${XDIR}$n/slapd.d
 	$SLAPCAT -F $CFDIR -b $BASEDN -l $TESTDIR/finaldb-$n.ldif
-	n=`expr $n + 1`
 done
 
-n=2
-while [ $n -le 4 ]; do
+for ((n=2; n<=$MMR; n++)); do
 	diff $TESTDIR/finaldb-1.ldif $TESTDIR/finaldb-$n.ldif > /dev/null 2>&1
 	RC=$?
 	if test $RC != 0 ; then
 		echo "ERROR: Final LDIF files differ"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
 		exit $RC
 	fi
-	n=`expr $n + 1`
 done
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
-
 echo ">>>>> Test succeeded"
-
-test $KILLSERVERS != no && wait
-
 exit 0
