tests: add checking slapadd exit code.
Change-Id: I652bd58a9784d88aaf9c46bc81dc93b24e045a58

diff --git a/tests/data/regressions/its8800/its8800 b/tests/data/regressions/its8800/its8800
--- a/tests/data/regressions/its8800/its8800
+++ b/tests/data/regressions/its8800/its8800
@@ -56,7 +56,19 @@ for ((n=1; n<=$MMR; n++)); do
 	DBNOSYNC=yes config_filter $BACKEND ${AC_conf[monitor]} < $ITSDIR/slapd-provider${n}.ldif > $CONFLDIF
 
 	$SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd(1) failed ($RC)!"
+		killservers
+		exit $RC
+	fi
 	$SLAPADD -F $CFDIR -q -b $BASEDN -l $ITSDIR/db.ldif
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd(2) failed ($RC)!"
+		killservers
+		exit $RC
+	fi
 done
 
 KILLPIDS=
@@ -122,6 +134,12 @@ mv $DBDIR.1 $DBDIR.1.orig
 mv $DBDIR.2 $DBDIR.2.orig
 mkdir -p $DBDIR.1 $DBDIR.2
 $SLAPADD -F $CFDIR -q -b $BASEDN -l $ITSDIR/db.ldif
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd(3) failed ($RC)!"
+	killservers
+	exit $RC
+fi
 echo "done"
 
 echo "Starting provider1 slapd on TCP/IP URI $URI1"
diff --git a/tests/scripts/test053-syncprov-glue b/tests/scripts/test053-syncprov-glue
--- a/tests/scripts/test053-syncprov-glue
+++ b/tests/scripts/test053-syncprov-glue
@@ -74,6 +74,12 @@ olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 
 EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd(1) failed ($RC)!"
+	killservers
+	exit $RC
+fi
 
 echo "Initializing provider2 configurations..."
 $SLAPADD -F $CFPRO2 -n 0 <<EOF
@@ -87,6 +93,12 @@ olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 
 EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd(2) failed ($RC)!"
+	killservers
+	exit $RC
+fi
 
 $SLAPADD -F $CFCONS -n 0 <<EOF
 dn: cn=config
@@ -98,6 +110,12 @@ objectClass: olcDatabaseConfig
 olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd(3) failed ($RC)!"
+	killservers
+	exit $RC
+fi
 
 echo "Starting provider slapd on TCP/IP port $PORT1..."
 cd $PRODDIR
