slapd: backport - Update accesslog format and syncrepl consumer (ITS#6545).
Make two successive modifications of the same attribute separate. This
lets the consumer interpret the log entry the same way as the server
that produced it.

Still depends on the log entry attributes being read in the same order
as they were written.

Change-Id: I0157c0411f521783ff1315caeec8e1f4c8bbf3ca

diff --git a/tests/scripts/test063-syncrepl-delta-multimaster b/tests/scripts/test063-syncrepl-delta-multimaster
--- a/tests/scripts/test063-syncrepl-delta-multimaster
+++ b/tests/scripts/test063-syncrepl-delta-multimaster
@@ -470,6 +470,23 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+$LDAPMODIFY -D "$MANAGERDN" -H $URI1 -w $PASSWD \
+	>> $TESTOUT 2>&1 << EOF
+dn: $THEDN
+changetype: modify
+replace: sn
+sn: Replaced later
+-
+replace: sn
+sn: Surname
+EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed for server 1 database ($RC)!"
+	killservers
+	exit $RC
+fi
+
 echo "Restoring replication between server 1 and 2..."
 n=1
 while [ $n -le $MMR ]; do
