tests: safewait and checks wait-result for always detect coredumps.
Change-Id: I926a3ea00a06f38937c065eab9962af3b686b21b

diff --git a/tests/scripts/test043-delta-syncrepl b/tests/scripts/test043-delta-syncrepl
--- a/tests/scripts/test043-delta-syncrepl
+++ b/tests/scripts/test043-delta-syncrepl
@@ -124,7 +124,7 @@ fi
 wait_syncrepl $PORT1 $PORT2
 
 echo -n "Stopping the provider ($PID), sleeping $SLEEP1 seconds and restarting it..."
-kill -HUP "$PID" && wait $PID && echo " Done" || echo " Failure ($?) !!!"
+kill -HUP "$PID" && safewait $PID && echo " Done" || echo " Failure ($?) !!!"
 sleep $SLEEP1
 
 echo "RESTART" >> $LOG1
@@ -280,7 +280,7 @@ if test $? != 0 ; then
 fi
 
 echo -n "Stopping consumer ($SLAVEPID) to test recovery..."
-kill -HUP $SLAVEPID && wait $SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
+kill -HUP $SLAVEPID && safewait $SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
 
 echo "Modifying more entries on the provider..."
 $LDAPMODIFY -v -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
diff --git a/tests/scripts/test045-syncreplication-proxied b/tests/scripts/test045-syncreplication-proxied
--- a/tests/scripts/test045-syncreplication-proxied
+++ b/tests/scripts/test045-syncreplication-proxied
@@ -218,7 +218,7 @@ fi
 
 CHECK=`expr $CHECK + 1`
 echo -n "$CHECK > Stopping the provider ($MASTERPID), sleeping $SLEEP1 seconds and restarting it..."
-kill -HUP $MASTERPID && wait $MASTERPID && echo " Done" || echo " Failure ($?) !!!"
+kill -HUP $MASTERPID && safewait $MASTERPID && echo " Done" || echo " Failure ($?) !!!"
 sleep $SLEEP1
 
 echo "======================= RESTART =======================" >> $LOG1
@@ -387,7 +387,7 @@ fi
 
 CHECK=`expr $CHECK + 1`
 echo -n "$CHECK > Stopping proxy ($PROXYPID) to test recovery..."
-kill -HUP $PROXYPID && wait $PROXYPID && echo " Done" || echo " Failure ($?) !!!"
+kill -HUP $PROXYPID && safewait $PROXYPID && echo " Done" || echo " Failure ($?) !!!"
 
 echo "Modifying more entries on the master..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
@@ -542,7 +542,7 @@ fi
 
 CHECK=`expr $CHECK + 1`
 echo -n "$CHECK > Stopping consumer ($SLAVEPID) to test recovery..."
-kill -HUP $SLAVEPID && wait $SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
+kill -HUP $SLAVEPID && safewait $SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
 
 echo "Modifying more entries on the master..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
@@ -620,7 +620,7 @@ if test $? != 0 ; then
 
 	echo "	test failed - master and slave databases differ (ignored by now)"
 	echo -n "	Stopping proxy ($PROXYPID) to see if it auto-recovers..."
-	kill -HUP $PROXYPID && wait $PROXYPID && echo " Done" || echo " Failure ($?) !!!"
+	kill -HUP $PROXYPID && safewait $PROXYPID && echo " Done" || echo " Failure ($?) !!!"
 
 	echo "	${CHECK}.1 > Restarting proxy..."
 	echo "======================= RESTART =======================" >> $LOG3
diff --git a/tests/scripts/test048-syncrepl-multiproxy b/tests/scripts/test048-syncrepl-multiproxy
--- a/tests/scripts/test048-syncrepl-multiproxy
+++ b/tests/scripts/test048-syncrepl-multiproxy
@@ -223,7 +223,7 @@ fi
 
 CHECK=`expr $CHECK + 1`
 echo -n "$CHECK > Stopping the provider ($MASTERPID), sleeping $SLEEP1 seconds and restarting it..."
-kill -HUP $MASTERPID && wait $MASTERPID && echo " Done" || echo " Failure ($?) !!!"
+kill -HUP $MASTERPID && safewait $MASTERPID && echo " Done" || echo " Failure ($?) !!!"
 sleep $SLEEP1
 
 echo "======================= RESTART =======================" >> $LOG1
@@ -408,7 +408,7 @@ fi
 
 CHECK=`expr $CHECK + 1`
 echo -n "$CHECK > Stopping slaves ($P1SLAVEPID, $R1SLAVEPID) to test recovery..."
-kill -HUP $P1SLAVEPID $R1SLAVEPID && wait $P1SLAVEPID $R1SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
+kill -HUP $P1SLAVEPID $R1SLAVEPID && safewait $P1SLAVEPID $R1SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
 
 echo "Modifying more entries on the master..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
