tests, configure: rework/fix TLS suite (#67, #68, #69, #70).
Change-Id: I10e4e3c00fb3fb5b697d5d51e38b3d3ba3242e46

diff --git a/tests/scripts/test070-delta-multimaster-ldaps b/tests/scripts/test070-delta-multimaster-ldaps
--- a/tests/scripts/test070-delta-multimaster-ldaps
+++ b/tests/scripts/test070-delta-multimaster-ldaps
@@ -1,9 +1,9 @@
-#! /bin/sh
-# $OpenLDAP$
-## This work is part of OpenLDAP Software <http://www.openldap.org/>.
-##
-## Copyright 1998-2017 The OpenLDAP Foundation.
+#!/bin/bash
+## $ReOpenLDAP$
+## Copyright 1998-2018 ReOpenLDAP AUTHORS: please see AUTHORS file.
 ## All rights reserved.
+##
+## This file is part of ReOpenLDAP.
 ##
 ## Redistribution and use in source and binary forms, with or without
 ## modification, are permitted only as authorized by the OpenLDAP
@@ -14,18 +14,18 @@
 ## <http://www.OpenLDAP.org/license.html>.
 
 echo "running defines.sh"
-. $SRCDIR/scripts/defines.sh
+. ${TOP_SRCDIR}/tests/scripts/defines.sh
 
-if test $WITH_TLS = no ; then
-        echo "TLS support not available, test skipped"
-        exit 0
+if test ${AC_conf[tls]} = no ; then
+	echo "TLS support not available, test skipped"
+	exit 0
 fi
 
-if test $SYNCPROV = syncprovno; then
+if test ${AC_conf[syncprov]} = no; then
 	echo "Syncrepl provider overlay not available, test skipped"
 	exit 0
 fi
-if test $ACCESSLOG = accesslogno; then
+if test ${AC_conf[accesslog]} = no; then
 	echo "Accesslog overlay not available, test skipped"
 	exit 0
 fi
@@ -93,17 +93,17 @@ olcTLSCertificateKeyFile: $TESTDIR/tls/private/localhost.key
 
 EOF
 
-if [ "$SYNCPROV" = syncprovmod -o "$ACCESSLOG" = accesslogmod ]; then
+if [ ${AC_conf[syncprov]} = mod -o ${AC_conf[accesslog]} = mod ]; then
   cat <<EOF >> $TMP
 dn: cn=module,cn=config
 objectClass: olcModuleList
 cn: module
 olcModulePath: $TESTWD/../servers/slapd/overlays
 EOF
-  if [ "$SYNCPROV" = syncprovmod ]; then
+  if [ ${AC_conf[syncprov]} = mod ]; then
   echo "olcModuleLoad: syncprov.la" >> $TMP
   fi
-  if [ "$ACCESSLOG" = accesslogmod ]; then
+  if [ ${AC_conf[accesslog]} = mod ]; then
   echo "olcModuleLoad: accesslog.la" >> $TMP
   fi
   echo "" >> $TMP
@@ -146,12 +146,14 @@ include: file://$ABS_SCHEMADIR/nis.ldif
 dn: olcDatabase={0}config,cn=config
 objectClass: olcDatabaseConfig
 olcDatabase: {0}config
+olcBiglock: local
 olcRootPW:< file://$CONFIGPWF
 
 dn: olcDatabase={1}$BACKEND,cn=config
 objectClass: olcDatabaseConfig
 ${nullExclude}objectClass: olc${BACKEND}Config
 olcDatabase: {1}$BACKEND
+olcBiglock: local
 olcSuffix: cn=log
 ${nullExclude}olcDbDirectory: ${DBDIR}.1
 olcRootDN: $MANAGERDN
@@ -168,13 +170,14 @@ dn: olcDatabase={2}$BACKEND,cn=config
 objectClass: olcDatabaseConfig
 ${nullExclude}objectClass: olc${BACKEND}Config
 olcDatabase: {2}$BACKEND
+olcBiglock: local
 olcSuffix: $BASEDN
 ${nullExclude}olcDbDirectory: ${DBDIR}.2
 olcRootDN: $MANAGERDN
 olcRootPW: $PASSWD
 olcSyncRepl: rid=001 provider=$PROVIDERURI binddn="$MANAGERDN" bindmethod=simple
   credentials=$PASSWD searchbase="$BASEDN" $SYNCTYPE
-  retry="3 +" timeout=3 logbase="cn=log"
+  retry="$SYNCREPL_RETRY" timeout=1 logbase="cn=log"
   logfilter="(&(objectclass=auditWriteObject)(reqresult=0))"
   syncdata=accesslog tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt
 olcMirrorMode: TRUE
@@ -199,7 +202,7 @@ PORT=`eval echo '$PORT'$n`
 echo "Starting server $n on TCP/IP port $PORT..."
 cd ${XDIR}${n}
 LOG=`eval echo '$LOG'$n`
-$SLAPD -F slapd.d -h $MYURI -d $LVL $TIMING > $LOG 2>&1 &
+$SLAPD -F slapd.d -h $MYURI $TIMING > $LOG 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
     echo PID $PID
@@ -207,24 +210,7 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$PID $KILLPIDS"
 cd $TESTWD
-
-echo "Using ldapsearch to check that server $n is running..."
-for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -o tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt -s base -b "" -H $MYURI \
-		'objectclass=*' > /dev/null 2>&1
-	RC=$?
-	if test $RC = 0 ; then
-		break
-	fi
-	echo "Waiting 5 seconds for slapd to start..."
-	sleep 5
-done
-
-if test $RC != 0 ; then
-	echo "ldapsearch failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
+check_running_uri $MYURI "$n-server" "-o tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt"
 
 if [ $n = 1 ]; then
 echo "Using ldapadd for context on server 1..."
@@ -233,7 +219,7 @@ $LDAPADD -D "$MANAGERDN" -H $SURIP1 -w $PASSWD -o tls_cacert=$TESTDIR/tls/ca/cer
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapadd failed for server $n database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 fi
@@ -247,43 +233,54 @@ $LDAPADD -D "$MANAGERDN" -H $SURIP1 -w $PASSWD -o tls_cacert=$TESTDIR/tls/ca/cer
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapadd failed for server $n database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-sleep $SLEEP1
+for retry in 1 2 3 4 last; do
+	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+	sleep $SLEEP1
 
-n=1
-while [ $n -le $MMR ]; do
-PORT=`expr $BASEPORT + $n`
-URI="ldaps://${LOCALIP}:$PORT/"
+	n=1
+	while [ $n -le $MMR ]; do
+		PORT=`expr $BASEPORT + $n`
+		URI="ldaps://${LOCALIP}:$PORT/"
 
-echo "Using ldapsearch to read all the entries from server $n..."
-$LDAPSEARCH -S "" -b "$BASEDN" -o tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt -D "$MANAGERDN" -H $URI -w $PASSWD  \
-	'objectclass=*' > $TESTDIR/server$n.out 2>&1
-RC=$?
+		echo "Using ldapsearch to read all the entries from server $n..."
+		$LDAPSEARCH -S "" -b "$BASEDN" -o tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt -D "$MANAGERDN" -H $URI -w $PASSWD  \
+			'objectclass=*' > $TESTDIR/server$n.out 2>&1
+		RC=$?
 
-if test $RC != 0 ; then
-	echo "ldapsearch failed at server $n ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-$LDIFFILTER < $TESTDIR/server$n.out > $TESTDIR/server$n.flt
-n=`expr $n + 1`
-done
+		if [ $RC != 0 ]; then
+			echo "ldapsearch failed at server $n ($RC)!"
+			killservers
+			exit $RC
+		fi
+		$LDIFFILTER < $TESTDIR/server$n.out > $TESTDIR/server$n.flt
+		n=`expr $n + 1`
+	done
 
-n=2
-while [ $n -le $MMR ]; do
-echo "Comparing retrieved entries from server 1 and server $n..."
-$CMP $MASTERFLT $TESTDIR/server$n.flt > $CMPOUT
+	n=2
+	while [ $n -le $MMR ]; do
+		echo "Comparing retrieved entries from server 1 and server $n..."
+		$CMP $MASTERFLT $TESTDIR/server$n.flt > $CMPOUT
+		RC=$?
 
-if test $? != 0 ; then
-	echo "test failed - server 1 and server $n databases differ"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 1
-fi
-n=`expr $n + 1`
+		if [ $RC != 0 ]; then
+			break;
+		fi
+		n=`expr $n + 1`
+	done
+
+	if [ $RC != 0 ]; then
+		if [ "$retry" != "last" ]; then
+			echo "Presumably more time is needed, retry..."
+			continue
+		fi
+		echo "test failed - server 1 and server $n databases differ"
+		killservers
+		exit 1
+	fi
 done
 
 echo "Using ldapadd to populate server 2..."
@@ -292,13 +289,13 @@ $LDAPADD -o tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt -D "$MANAGERDN" -H 
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapadd failed for server 2 database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
 THEDN="cn=James A Jones 2,ou=Alumni Association,ou=People,dc=example,dc=com"
-sleep 1
-for i in 1 2 3; do
+sleep 0.1
+for i in 1 2 3 4 5; do
 	$LDAPSEARCH -S "" -b "$THEDN" -o tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt -H $SURIP1 \
 		-s base '(objectClass=*)' entryCSN > "${MASTEROUT}.$i" 2>&1
 	RC=$?
@@ -309,7 +306,7 @@ for i in 1 2 3; do
 
 	if test $RC != 32 ; then
 		echo "ldapsearch failed at slave ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		killservers
 		exit $RC
 	fi
 
@@ -329,7 +326,7 @@ RC=$?
 
 if test $RC != 0 ; then
 	echo "ldapsearch failed at server $n ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 $LDIFFILTER < $TESTDIR/server$n.out > $TESTDIR/server$n.flt
@@ -343,7 +340,7 @@ $CMP $MASTERFLT $TESTDIR/server$n.flt > $CMPOUT
 
 if test $? != 0 ; then
 	echo "test failed - server 1 and server $n databases differ"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit 1
 fi
 n=`expr $n + 1`
@@ -361,7 +358,7 @@ changetype: modify
 replace: olcSyncRepl
 olcSyncRepl: rid=001 provider=$PROVIDERURI binddn="$MANAGERDN" bindmethod=simple
   credentials=InvalidPw searchbase="$BASEDN" $SYNCTYPE
-  retry="3 +" timeout=3 logbase="cn=log"
+  retry="$SYNCREPL_RETRY" timeout=1 logbase="cn=log"
   logfilter="(&(objectclass=auditWriteObject)(reqresult=0))"
   syncdata=accesslog tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt
 -
@@ -372,7 +369,7 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server $n config ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 n=`expr $n + 1`
@@ -390,7 +387,7 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server 1 database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
@@ -405,7 +402,7 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server 2 database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
@@ -423,7 +420,7 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server 1 database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
@@ -441,7 +438,7 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server 2 database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
@@ -459,7 +456,7 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server 1 database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
@@ -477,7 +474,7 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server 2 database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
@@ -494,7 +491,7 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server 1 database ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 
@@ -510,7 +507,7 @@ changetype: modify
 replace: olcSyncRepl
 olcSyncRepl: rid=001 provider=$PROVIDERURI binddn="$MANAGERDN" bindmethod=simple
   credentials=$PASSWD searchbase="$BASEDN" $SYNCTYPE
-  retry="3 +" timeout=3 logbase="cn=log"
+  retry="$SYNCREPL_RETRY" timeout=1 logbase="cn=log"
   logfilter="(&(objectclass=auditWriteObject)(reqresult=0))"
   syncdata=accesslog tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt
 -
@@ -521,51 +518,58 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server $n config ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	killservers
 	exit $RC
 fi
 n=`expr $n + 1`
 done
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-sleep $SLEEP1
+for retry in 1 2 3 4 last; do
+	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+	sleep $SLEEP1
 
-n=1
-while [ $n -le $MMR ]; do
-PORT=`expr $BASEPORT + $n`
-URI="ldaps://${LOCALIP}:$PORT/"
+	n=1
+	while [ $n -le $MMR ]; do
+		PORT=`expr $BASEPORT + $n`
+		URI="ldaps://${LOCALIP}:$PORT/"
 
-echo "Using ldapsearch to read all the entries from server $n..."
-$LDAPSEARCH -o tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt -S "" -b "$BASEDN" -D "$MANAGERDN" -H $URI -w $PASSWD  \
-	'objectclass=*' > $TESTDIR/server$n.out 2>&1
-RC=$?
+		echo "Using ldapsearch to read all the entries from server $n..."
+		$LDAPSEARCH -o tls_cacert=$TESTDIR/tls/ca/certs/testsuiteCA.crt -S "" -b "$BASEDN" -D "$MANAGERDN" -H $URI -w $PASSWD  \
+			'objectclass=*' > $TESTDIR/server$n.out 2>&1
+		RC=$?
 
-if test $RC != 0 ; then
-	echo "ldapsearch failed at server $n ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-$LDIFFILTER -s a < $TESTDIR/server$n.out > $TESTDIR/server$n.flt
-n=`expr $n + 1`
+		if [ $RC != 0 ]; then
+			echo "ldapsearch failed at server $n ($RC)!"
+			killservers
+			exit $RC
+		fi
+		$LDIFFILTER -s a < $TESTDIR/server$n.out > $TESTDIR/server$n.flt
+		n=`expr $n + 1`
+	done
+
+	n=2
+	while [ $n -le $MMR ]; do
+		echo "Comparing retrieved entries from server 1 and server $n..."
+		$CMP $MASTERFLT $TESTDIR/server$n.flt > $CMPOUT
+		RC=$?
+
+		if [ $RC != 0 ]; then
+			break
+		fi
+		n=`expr $n + 1`
+	done
+
+	if [ $RC != 0 ]; then
+		if [ "$retry" != "last" ]; then
+			echo "Presumably more time is needed, retry..."
+			continue
+		fi
+		echo "test failed - server 1 and server $n databases differ"
+		killservers
+		exit 1
+	fi
 done
 
-n=2
-while [ $n -le $MMR ]; do
-echo "Comparing retrieved entries from server 1 and server $n..."
-$CMP $MASTERFLT $TESTDIR/server$n.flt > $CMPOUT
-
-if test $? != 0 ; then
-	echo "test failed - server 1 and server $n databases differ"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 1
-fi
-n=`expr $n + 1`
-done
-
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
-
+killservers
 echo ">>>>> Test succeeded"
-
-test $KILLSERVERS != no && wait
-
 exit 0
