test: reworking of waiting for syncrepl for speedup.
Change-Id: If12ef6f3f0582b0e37303fbe0debb4199213a17e

diff --git a/tests/scripts/test043-delta-syncrepl b/tests/scripts/test043-delta-syncrepl
--- a/tests/scripts/test043-delta-syncrepl
+++ b/tests/scripts/test043-delta-syncrepl
@@ -120,12 +120,13 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT2
+
+echo -n "Stopping the provider ($PID), sleeping $SLEEP1 seconds and restarting it..."
+kill -HUP "$PID" && wait $PID && echo " Done" || echo " Failure ($?) !!!"
 sleep $SLEEP1
 
-echo "Stopping the provider, sleeping 10 seconds and restarting it..."
-kill -HUP "$PID"
-sleep 10
 echo "RESTART" >> $LOG1
 $SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING >> $LOG1 2>&1 &
 PID=$!
@@ -239,8 +240,8 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-sleep $SLEEP1
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT2
 
 echo "Using ldapsearch to read all the entries from the provider..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -278,9 +279,8 @@ if test $? != 0 ; then
 	exit 1
 fi
 
-echo "Stopping consumer to test recovery..."
-kill -HUP $SLAVEPID
-sleep 10
+echo -n "Stopping consumer ($SLAVEPID) to test recovery..."
+kill -HUP $SLAVEPID && wait $SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
 
 echo "Modifying more entries on the provider..."
 $LDAPMODIFY -v -D "$BJORNSDN" -h $LOCALHOST -p $PORT1 -w bjorn >> \
@@ -321,8 +321,8 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$PID $SLAVEPID"
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-sleep $SLEEP1
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT2
 
 if test ! $BACKLDAP = "ldapno" ; then
 	echo "Try updating the consumer slapd..."
@@ -343,8 +343,8 @@ EOMODS
 		exit $RC
 	fi
 
-	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-	sleep $SLEEP1
+	#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+	wait_syncrepl $PORT1 $PORT2
 fi
 
 echo "Using ldapsearch to read all the entries from the provider..."
diff --git a/tests/scripts/test045-syncreplication-proxied b/tests/scripts/test045-syncreplication-proxied
--- a/tests/scripts/test045-syncreplication-proxied
+++ b/tests/scripts/test045-syncreplication-proxied
@@ -178,27 +178,7 @@ if test $RC != 0 ; then
 fi
 
 # check slave contextCSN
-sleep 0.1
-for i in 1 2 3 4 5; do
-	$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-		-s base '(objectClass=*)' contextCSN > "${SLAVEOUT}.$CHECK" 2>&1
-	RC=$?
-
-	if test $RC != 0 ; then
-		echo "ldapsearch failed at slave ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-
-	$CMP ${MASTEROUT}.$CHECK ${SLAVEOUT}.$CHECK > $CMPOUT
-
-	if test $? = 0 ; then
-		break
-	fi
-
-	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-	sleep $SLEEP1
-done
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -237,10 +217,9 @@ if test $? != 0 ; then
 fi
 
 CHECK=`expr $CHECK + 1`
-echo "$CHECK > Stopping the provider, sleeping $SLEEP2 seconds and restarting it..."
-kill -HUP "$MASTERPID"
-wait $MASTERPID
-sleep $SLEEP2
+echo -n "$CHECK > Stopping the provider ($MASTERPID), sleeping $SLEEP1 seconds and restarting it..."
+kill -HUP $MASTERPID && wait $MASTERPID && echo " Done" || echo " Failure ($?) !!!"
+sleep $SLEEP1
 
 echo "======================= RESTART =======================" >> $LOG1
 $SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING >> $LOG1 2>&1 &
@@ -368,26 +347,7 @@ if test $RC != 0 ; then
 fi
 
 # check slave contextCSN
-sleep 0.1
-for i in 1 2 3 4 5; do
-	$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-		-s base '(objectClass=*)' contextCSN > "${SLAVEOUT}.$CHECK" 2>&1
-	RC=$?
-
-	if test $RC != 0 ; then
-		echo "ldapsearch failed at slave ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-
-	$CMP ${MASTEROUT}.$CHECK ${SLAVEOUT}.$CHECK > $CMPOUT
-	if test $? = 0 ; then
-		break
-	fi
-
-	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-	sleep $SLEEP1
-done
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -426,9 +386,8 @@ if test $? != 0 ; then
 fi
 
 CHECK=`expr $CHECK + 1`
-echo "$CHECK > Stopping proxy to test recovery..."
-kill -HUP $PROXYPID
-wait $PROXYPID
+echo -n "$CHECK > Stopping proxy ($PROXYPID) to test recovery..."
+kill -HUP $PROXYPID && wait $PROXYPID && echo " Done" || echo " Failure ($?) !!!"
 
 echo "Modifying more entries on the master..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
@@ -475,26 +434,7 @@ if test $RC != 0 ; then
 fi
 
 # check slave contextCSN
-for i in 1 2 3 4 5; do
-	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-	sleep $SLEEP1
-
-	$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-		-s base '(objectClass=*)' contextCSN > "${SLAVEOUT}.$CHECK" 2>&1
-	RC=$?
-
-	if test $RC != 0 ; then
-		echo "ldapsearch failed at slave ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-
-	$CMP ${MASTEROUT}.$CHECK ${SLAVEOUT}.$CHECK > $CMPOUT
-
-	if test $? = 0 ; then
-		break
-	fi
-done
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -562,26 +502,7 @@ if test $RC != 0 ; then
 fi
 
 # check slave contextCSN
-sleep 0.1
-for i in 1 2 3; do
-	$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-		-s base '(objectClass=*)' contextCSN > "${SLAVEOUT}.$CHECK" 2>&1
-	RC=$?
-
-	if test $RC != 0 ; then
-		echo "ldapsearch failed at slave ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-
-	$CMP ${MASTEROUT}.$CHECK ${SLAVEOUT}.$CHECK > $CMPOUT
-	if test $? = 0 ; then
-		break
-	fi
-
-	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-	sleep $SLEEP1
-done
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -620,9 +541,8 @@ if test $? != 0 ; then
 fi
 
 CHECK=`expr $CHECK + 1`
-echo "$CHECK > Stopping consumer to test recovery..."
-kill -HUP $SLAVEPID
-wait $SLAVEPID
+echo -n "$CHECK > Stopping consumer ($SLAVEPID) to test recovery..."
+kill -HUP $SLAVEPID && wait $SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
 
 echo "Modifying more entries on the master..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
@@ -634,8 +554,8 @@ drink: Mad Dog 20/20
 
 EOMODS
 
-echo "Waiting $SLEEP2 seconds for syncrepl to retry..."
-sleep $SLEEP2
+echo "Waiting 3 seconds for syncrepl to retry..."
+sleep 3
 
 echo "Restarting consumer..."
 echo "======================= RESTART =======================" >> $LOG2
@@ -658,27 +578,7 @@ if test $RC != 0 ; then
 fi
 
 # check slave contextCSN
-
-for i in 1 2 3 4 5; do
-	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-	sleep $SLEEP1
-
-	$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-		-s base '(objectClass=*)' contextCSN > "${SLAVEOUT}.$CHECK" 2>&1
-	RC=$?
-
-	if test $RC != 0 ; then
-		echo "ldapsearch failed at slave ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-
-	$CMP ${MASTEROUT}.$CHECK ${SLAVEOUT}.$CHECK > $CMPOUT
-
-	if test $? = 0 ; then
-		break
-	fi
-done
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -719,9 +619,8 @@ if test $? != 0 ; then
 	fi
 
 	echo "	test failed - master and slave databases differ (ignored by now)"
-	echo "	Stopping proxy to see if it auto-recovers..."
-	kill -HUP $PROXYPID
-	wait $PROXYPID
+	echo -n "	Stopping proxy ($PROXYPID) to see if it auto-recovers..."
+	kill -HUP $PROXYPID && wait $PROXYPID && echo " Done" || echo " Failure ($?) !!!"
 
 	echo "	${CHECK}.1 > Restarting proxy..."
 	echo "======================= RESTART =======================" >> $LOG3
@@ -733,8 +632,8 @@ if test $? != 0 ; then
 	fi
 	KILLPIDS="$MASTERPID $SLAVEPID $PROXYPID"
 
-	echo "	Waiting $SLEEP2 seconds for syncrepl to receive changes..."
-	sleep $SLEEP2
+	#echo "	Waiting $SLEEP2 seconds for syncrepl to receive changes..."
+	wait_syncrepl $PORT1 $PORT2
 
 	#echo "Using ldapsearch to read all the entries from the slave..."
 	$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
@@ -798,27 +697,7 @@ if test $RC != 0 ; then
 fi
 
 # check slave contextCSN
-sleep 0.1
-for i in 1 2 3; do
-	$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
-		-s base '(objectClass=*)' contextCSN > "${SLAVEOUT}.$CHECK" 2>&1
-	RC=$?
-
-	if test $RC != 0 ; then
-		echo "ldapsearch failed at slave ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-
-	$CMP ${MASTEROUT}.$CHECK ${SLAVEOUT}.$CHECK > $CMPOUT
-
-	if test $? = 0 ; then
-		break
-	fi
-
-	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-	sleep $SLEEP1
-done
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
diff --git a/tests/scripts/test048-syncrepl-multiproxy b/tests/scripts/test048-syncrepl-multiproxy
--- a/tests/scripts/test048-syncrepl-multiproxy
+++ b/tests/scripts/test048-syncrepl-multiproxy
@@ -156,8 +156,8 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-sleep $SLEEP1
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -195,6 +195,9 @@ if test $? != 0 ; then
 	exit 1
 fi
 
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT3
+
 #echo "Using ldapsearch to read all the entries from the R1 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT3 \
 	'(objectClass=*)' > "${SLAVEOUT}.1" 2>&1
@@ -219,10 +222,9 @@ if test $? != 0 ; then
 fi
 
 CHECK=`expr $CHECK + 1`
-echo "$CHECK > Stopping the provider, sleeping $SLEEP2 seconds and restarting it..."
-kill -HUP "$MASTERPID"
-wait $MASTERPID
-sleep $SLEEP2
+echo -n "$CHECK > Stopping the provider ($MASTERPID), sleeping $SLEEP1 seconds and restarting it..."
+kill -HUP $MASTERPID && wait $MASTERPID && echo " Done" || echo " Failure ($?) !!!"
+sleep $SLEEP1
 
 echo "======================= RESTART =======================" >> $LOG1
 $SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING >> $LOG1 2>&1 &
@@ -339,8 +341,8 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-sleep $SLEEP1
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -378,6 +380,9 @@ if test $? != 0 ; then
 	exit 1
 fi
 
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT3
+
 #echo "Using ldapsearch to read all the entries from the R1 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT3 \
 	'(objectClass=*)' > "${SLAVEOUT}.2" 2>&1
@@ -402,10 +407,8 @@ if test $? != 0 ; then
 fi
 
 CHECK=`expr $CHECK + 1`
-echo "$CHECK > Stopping slaves to test recovery..."
-kill -HUP $P1SLAVEPID $R1SLAVEPID
-wait $P1SLAVEPID
-wait $R1SLAVEPID
+echo -n "$CHECK > Stopping slaves ($P1SLAVEPID, $R1SLAVEPID) to test recovery..."
+kill -HUP $P1SLAVEPID $R1SLAVEPID && wait $P1SLAVEPID $R1SLAVEPID && echo " Done" || echo " Failure ($?) !!!"
 
 echo "Modifying more entries on the master..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD >> \
@@ -450,8 +453,8 @@ if test $WAIT != 0 ; then
 fi
 KILLPIDS="$MASTERPID $P1SLAVEPID $R1SLAVEPID"
 
-echo "Waiting $SLEEP2 seconds for syncrepl to receive changes..."
-sleep $SLEEP2
+#echo "Waiting $SLEEP2 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -488,6 +491,9 @@ if test $? != 0 ; then
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit 1
 fi
+
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT3
 
 #echo "Using ldapsearch to read all the entries from the R1 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT3 \
@@ -531,8 +537,8 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-sleep $SLEEP1
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT2
 
 #echo "Using ldapsearch to read all the entries from the master..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
@@ -569,6 +575,9 @@ if test $? != 0 ; then
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit 1
 fi
+
+#echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+wait_syncrepl $PORT1 $PORT3
 
 #echo "Using ldapsearch to read all the entries from the R1 slave..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT3 \
