tests: added to the test-48 check/wait for server on restart, to avoid sporadic failures.
Change-Id: I26a62e226d51241fe564d46040be68060d21efdf

diff --git a/tests/scripts/test048-syncrepl-multiproxy b/tests/scripts/test048-syncrepl-multiproxy
--- a/tests/scripts/test048-syncrepl-multiproxy
+++ b/tests/scripts/test048-syncrepl-multiproxy
@@ -452,6 +452,37 @@ if test $WAIT != 0 ; then
     read foo
 fi
 KILLPIDS="$MASTERPID $P1SLAVEPID $R1SLAVEPID"
+sleep 0.1
+
+echo "Using ldapsearch to check that P1 slave slapd is running..."
+for i in 1 2 3 4 5; do
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT2 \
+		'(objectClass=*)' > /dev/null 2>&1
+	RC=$?
+	if test $RC = 0 ; then
+		break
+	fi
+	echo "Waiting $i seconds for slapd to start..."
+	sleep $i
+done
+
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	killservers
+	exit $RC
+fi
+
+echo "Using ldapsearch to check that R1 slave slapd is running..."
+for i in 1 2 3 4 5; do
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT3 \
+		'(objectClass=*)' > /dev/null 2>&1
+	RC=$?
+	if test $RC = 0; then
+		break
+	fi
+	echo "Waiting $i seconds for slapd to start..."
+	sleep $i
+done
 
 #echo "Waiting $SLEEP2 seconds for syncrepl to receive changes..."
 wait_syncrepl $PORT1 $PORT2
